# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20171201_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='overview',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
